import { PluginAction } from 'src/stores/view/subscriptions/effects/align-branch/align-branch';

const actionPriorityRecord: Partial<Record<PluginAction['type'], number>> = {
    'view/life-cycle/mount': 100,
    'view/update-active-branch?source=document': 90,
    'view/set-active-node/keyboard-jump': 90,
    'view/set-active-node/sequential/select-next': 90,
    'view/set-active-node/keyboard': 90,
    'view/set-active-node/history/select-previous': 90,
    'view/set-active-node/history/select-next': 90,
    'view/set-active-node/mouse': 90,
    'view/set-active-node/mouse-silent': 0,
    'view/set-active-node/search': 30,
    'view/align-branch/center-node': 30,
    'view/align-branch/reveal-node': 30,
    'view/selection/select-all': 30,
    'document/update-node-content': 30,
    'view/set-active-node/document': 20,
    'view/editor/disable-main-editor': 20,
    'view/editor/enable-main-editor': 20,
    'view/outline/toggle-collapse-node': 10,
    'view/outline/refresh-collapsed-nodes': 10,
    'view/outline/toggle-collapse-all': 10,
    'document/format-headings': 10,
    'view/left-sidebar/set-width': 10,
    'plugin/echo/workspace/active-leaf-change': 10,
    'plugin/echo/workspace/resize': 10,
    'plugin/echo/workspace/layout-ready': 10,
    'plugin/documents/update-active-view-of-document': 10,
    'settings/view/toggle-minimap': 10,
    'view/left-sidebar/toggle': 10,
    'settings/view/layout/set-card-width': 10,
    'settings/view/layout/set-cards-gap': 10,
    'settings/view/layout/set-min-card-height': 10,
    'view/modes/gap-between-cards/toggle': 10,
    'view/search/set-results': 10,
    'search/view/toggle-show-all-nodes': 10,
    'view/search/set-query': 10,
    'view/search/toggle-input': 10,
    'view/search/toggle-fuzzy-mode': 10,
    'settings/view/toggle-horizontal-scrolling-mode': 10,
    'settings/view/toggle-vertical-scrolling-mode': 10,
    'settings/view/layout/set-limit-card-height': 10,
    'settings/view/set-zoom-level': 10,
    'settings/view/modes/toggle-outline-mode': 10,
    'settings/view/set-node-indentation-width': 10,
};

export const actionPriority = new Map(
    Object.entries(actionPriorityRecord) as [PluginAction['type'], number][],
);
